image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      # 启动 MySQL
      mkdir -p /workspace/mysql-data
      mysqld_safe --datadir=/workspace/mysql-data &
      sleep 5
      # 创建数据库并导入 SQL
      mysql -e "CREATE DATABASE IF NOT EXISTS testdb;"
      if [ -f init.sql ]; then
        mysql testdb < init.sql
      fi
      # 安装 PHP 依赖
      composer install
  - command: php -S 0.0.0.0:8000
    openMode: preview