image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      # 启动 MySQL 服务
      sudo service mysql start

      # 创建数据库
      mysql -e "CREATE DATABASE IF NOT EXISTS testdb;"

      # 导入 SQL（如果存在）
      if [ -f init.sql ]; then
        mysql testdb < init.sql
      fi
    command: |
      # 启动 PHP 内置服务器
      php -S 0.0.0.0:8080
ports:
  - port: 8080
    onOpen: open-browser