image:
  file: .gitpod.Dockerfile

# 启动 MySQL 容器
services:
  - image: mysql:8.0
    env:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - 3306:3306
    command: ["--default-authentication-plugin=mysql_native_password"]

tasks:
  - init: |
      # 等待 MySQL 启动
      echo "Waiting for MySQL..."
      sleep 10

      # 导入 SQL 初始化数据
      mysql -h 127.0.0.1 -P 3306 -u root -proot testdb < init.sql

  - command: php -S 0.0.0.0:8080 -t /workspace
ports:
  - port: 8080
    onOpen: open-preview
    