image:
  file: .gitpod.Dockerfile

tasks:
  - init: echo "Workspace ready. SQLite will auto-create test.db on first run."
    command: php -S 0.0.0.0:8080
ports:
  - port: 8080
    onOpen: open-browser