name: Auto Commit HTML

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Commit and push changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # 添加所有新文件和修改
          git add .
          
          # 提交，如果没有更改就跳过
          git commit -m "自动创建英语单词学习HTML" || echo "没有更改可提交"
          
          # 设置远程 URL 使用 PAT
          git remote set-url origin https://$PAT_TOKEN@github.com/guomengtao/hello-php.git
          
          # 推送到 main
          git push origin main
